### PR TITLE
Dual Staking Option

### PR DESCRIPTION
**Pull request by brittcyr**

### CODE REVIEW

**Review by DonDuala — APPROVED** [review]
Changed labels & reordered fields. In comments put tooltips to add if possible. Could instead be explainer text in the box or below

**Comment by brittcyr** [comment]
Added tooltips, but changed the comments to reflect what the account actually is where it was misleading

**Review by DonDuala — COMMENTED** [review]
We should make some mention of the convention around Upside vs Downside or allow selection of type to flip the base & quote and recalc the strike properly

**Comment by brittcyr** [comment]
I made it more clear what each token's role is, but dont want to reference downside explicitly or flip the tokens for the user since that gets more confusing and downside isnt really a first class supported concept anywhere in the code.

**Pull request merged**
